name: Pulumi
on:
  pull_request:
    paths:
      - "infrastructure/**"
      - ".github/workflows/pull_request.yml"
jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    environment: mom-jokes-dev

    defaults:
      run:
        working-directory: infrastructure

    steps:
      - name: Checkout repo
        uses: actions/checkout@4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json

      - name: Install dependencies
        run: npm install

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Pulumi preview
        uses: pulumi/actions@v6
        with:
          command: preview
          stack-name: dev # When using an individual account, only use stack-name.
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
